### ISSUE TITLE
How do you integrate with your own models?

### ISSUE THREAD

**Issue by Immortalin** [bigmachine-io/blackbook#2]
If you need to add a field to the user model, what is the recommended way of doing so besides modifying the blackbook source?

**Comment by robconery** [comment]
The profile field is a map, stored as JSONB so you should be able to use that. What kind of field are you thinking about?

**Comment by Immortalin** [comment]
What I meant is how do you extend the user model etc. E.g. when you already have a user model and integrating blackbook overrides the default one etc. How should you properly integrate with it? If you create a new application, how should you add your own fields to the user model without having to edit the blackbook source? Apologies if thr questions are a bit vague, I am rather new to elixir.

**Comment by robconery** [comment]
Hmmm. Well, I would import the data to Blackbook that already exists; fitting the old bits to the new. There's a flexible profile field there which means you can store anything on it (Name, Twitter handle, whatever).

**Comment by Immortalin** [comment]
Guess I will have to fork and edit source then :(

**Comment by Immortalin** [comment]
@robconery is there a way to get blackbook to create the schema within the user application instead? Maybe a mix task, something like the phoenix template generators. [Other libraries](https://github.com/trenpixster/addict) allow this.

**Comment by robconery** [comment]
Yes I suppose. Do feel free to fork; if you find ways to improve a PR is always welcome. Also - if you give me more of an idea as to what you're trying to do (with details) I would be happy to offer some ideas or change things around.

Also - I'll be revamping the source here quite soon. If you'd like to help (as far as it would help your situation) that would be very nice :).

**Comment by Immortalin** [comment]
@robconery to clarify, I meant something like [this](https://github.com/opendrops/passport) i.e. the schema is on the user side. I am currently working on a pull request which adds a mix generator task to generate the schema. However, I am not too sure how to modify blackbook to use an external schema instead.
